import type { LexEntry } from './index';

// Buzzword -> plain-English mappings with fluff weights.
// empty:true  = meaningless filler (weight 2.0)
// empty:false = jargon with a real plain synonym (weight 1.0-1.5)
export const DATA: LexEntry[] = [
  { term: 'cutting-edge', plain: 'new', weight: 2, empty: true },
  { term: 'bleeding-edge', plain: 'new (unproven)', weight: 2, empty: true },
  { term: 'state-of-the-art', plain: 'new', weight: 2, empty: true },
  { term: 'best-in-class', plain: '(no meaning — unproven claim)', weight: 2, empty: true },
  { term: 'best-of-breed', plain: '(no meaning)', weight: 2, empty: true },
  { term: 'world-class', plain: '(no meaning)', weight: 2, empty: true },
  { term: 'industry-leading', plain: '(no meaning — unverifiable)', weight: 2, empty: true },
  { term: 'seamless', plain: 'works without extra setup', weight: 1.5, empty: false },
  { term: 'frictionless', plain: 'easy to use', weight: 1.5, empty: false },
  { term: 'turnkey', plain: 'ready to use', weight: 1, empty: false },
  { term: 'end-to-end', plain: 'covers the whole process', weight: 1, empty: false },
  { term: 'synergy', plain: '(no meaning)', weight: 2, empty: true },
  { term: 'paradigm', plain: '(no meaning)', weight: 2, empty: true },
  { term: 'leverage', plain: 'use', weight: 1, empty: false },
  { term: 'next-generation', plain: 'new version', weight: 2, empty: true },
  { term: 'next-level', plain: '(no meaning)', weight: 2, empty: true },
  { term: 'disruptive', plain: '(no meaning)', weight: 2, empty: true },
  { term: 'game-changing', plain: '(no meaning)', weight: 2, empty: true },
  { term: 'revolutionary', plain: '(no meaning)', weight: 2, empty: true },
  { term: 'transformative', plain: '(no meaning)', weight: 2, empty: true },
  { term: 'robust', plain: 'reliable', weight: 1, empty: false },
  { term: 'scalable', plain: 'handles growth', weight: 1, empty: false },
  { term: 'innovative', plain: '(no meaning)', weight: 2, empty: true },
  { term: 'holistic', plain: 'covers everything', weight: 1.5, empty: false },
  { term: 'mission-critical', plain: 'important', weight: 1, empty: false },
  { term: 'value-add', plain: 'benefit', weight: 1.5, empty: false },
  { term: 'thought leader', plain: '(no meaning)', weight: 2, empty: true },
  { term: 'low-hanging fruit', plain: 'easy win', weight: 1, empty: false },
  { term: 'move the needle', plain: 'make a difference', weight: 1.5, empty: false },
  { term: 'circle back', plain: 'follow up', weight: 1, empty: false },
  { term: 'deep dive', plain: 'detailed look', weight: 1, empty: false },
  { term: 'streamline', plain: 'simplify', weight: 1, empty: false },
  { term: 'empower', plain: 'help', weight: 1.5, empty: false },
  { term: 'unlock', plain: 'enable', weight: 1.5, empty: false },
  { term: 'future-proof', plain: '(no meaning)', weight: 2, empty: true },
  { term: 'operationalize', plain: 'put into practice', weight: 1.5, empty: false },
  { term: 'ecosystem', plain: 'set of connected tools', weight: 1, empty: false },
  { term: 'supercharge', plain: 'speed up', weight: 1.5, empty: false },
  { term: 'optimize', plain: 'improve', weight: 1, empty: false },
  { term: 'elevate', plain: 'improve', weight: 1.5, empty: false },
  { term: 'ai-native', plain: 'has some AI features', weight: 1.5, empty: false },
  { term: 'cloud-first', plain: 'runs online', weight: 1, empty: false },
  { term: 'digital transformation', plain: '(no meaning)', weight: 2, empty: true },
  { term: 'operational excellence', plain: '(no meaning)', weight: 2, empty: true },
  { term: 'intelligent orchestration', plain: '(no meaning)', weight: 2, empty: true },
  // Real-world platform jargon (observed on live pages, 2026-07-12).
  { term: 'agentic', plain: '(vague — uses AI agents, somehow)', weight: 2, empty: true },
  { term: 'unified platform', plain: '(no meaning — everything is a "platform")', weight: 2, empty: true },
  { term: 'open platform', plain: '(vague)', weight: 1.5, empty: true },
  { term: 'trusted platform', plain: '(no meaning — self-asserted)', weight: 2, empty: true },
  { term: 'monetize', plain: 'make money from', weight: 1, empty: false },
  { term: 'purpose-built', plain: 'made for this', weight: 1, empty: false },
  { term: 'enterprise-grade', plain: '(vague — "serious enough for big companies")', weight: 1.5, empty: true },
  { term: 'battle-tested', plain: 'used in production', weight: 1, empty: false },
  { term: 'reimagine', plain: '(no meaning)', weight: 2, empty: true },
  { term: 'accelerate', plain: 'speed up', weight: 1, empty: false },
  { term: 'orchestrate', plain: 'coordinate', weight: 1, empty: false },
  { term: 'hyperscale', plain: '(vague — handles a lot)', weight: 1.5, empty: true },
  { term: 'single pane of glass', plain: 'one screen for everything', weight: 1.5, empty: false },
  { term: 'north star', plain: 'main goal', weight: 1.5, empty: false },
  { term: 'first-class', plain: '(no meaning)', weight: 2, empty: true },
  { term: 'out-of-the-box', plain: 'works without setup', weight: 1, empty: false },
  { term: 'plug-and-play', plain: 'works without setup', weight: 1, empty: false },
];
